const currencySymbols: Record<string, { name: string; symbol: string }> = {
    AED: { name: 'UAE Dirham', symbol: 'د.إ' },
    AFN: { name: 'Afghani', symbol: '؋' },
    ALL: { name: 'Lek', symbol: 'L' },
    AMD: { name: 'Armenian Dram', symbol: 'դր.' },
    ANG: { name: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
    AOA: { name: 'Kwanza', symbol: 'Kz' },
    ARS: { name: 'Argentine Peso', symbol: '$' },
    AUD: { name: 'Australian Dollar', symbol: '$' },
    AWG: { name: 'Aruban Florin', symbol: 'ƒ' },
    AZN: { name: 'Azerbaijanian Manat', symbol: '₼' },
    BAM: { name: 'Convertible Mark', symbol: 'КМ' },
    BBD: { name: 'Barbados Dollar', symbol: '$' },
    BDT: { name: 'Taka', symbol: '৳' },
    BGN: { name: 'Bulgarian Lev', symbol: 'лв' },
    BHD: { name: 'Bahraini Dinar', symbol: 'ب.د' },
    BIF: { name: 'Burundi Franc', symbol: 'Fr' },
    BMD: { name: 'Bermudian Dollar', symbol: '$' },
    BND: { name: 'Brunei Dollar', symbol: '$' },
    BOB: { name: 'Boliviano', symbol: 'Bs.' },
    BOV: { name: 'Mvdol', symbol: 'Bs.' },
    BRL: { name: 'Brazilian Real', symbol: 'R$' },
    BSD: { name: 'Bahamian Dollar', symbol: '$' },
    BTN: { name: 'Ngultrum', symbol: 'Nu.' },
    BWP: { name: 'Pula', symbol: 'P' },
    BYN: { name: 'Belarussian Ruble', symbol: 'Br' },
    BZD: { name: 'Belize Dollar', symbol: '$' },
    CAD: { name: 'Canadian Dollar', symbol: '$' },
    CDF: { name: 'Congolese Franc', symbol: 'Fr' },
    CHF: { name: 'Swiss Franc', symbol: 'CHF' },
    CLF: { name: 'Unidades de fomento', symbol: 'UF' },
    CLP: { name: 'Chilean Peso', symbol: '$' },
    CNY: { name: 'Yuan Renminbi', symbol: '¥' },
    COP: { name: 'Colombian Peso', symbol: '$' },
    CRC: { name: 'Costa Rican Colon', symbol: '₡' },
    CUC: { name: 'Peso Convertible', symbol: '$' },
    CUP: { name: 'Cuban Peso', symbol: '$' },
    CVE: { name: 'Cape Verde Escudo', symbol: '$' },
    CZK: { name: 'Czech Koruna', symbol: 'Kč' },
    DJF: { name: 'Djibouti Franc', symbol: 'Fdj' },
    DKK: { name: 'Danish Krone', symbol: 'kr' },
    DOP: { name: 'Dominican Peso', symbol: '$' },
    DZD: { name: 'Algerian Dinar', symbol: 'د.ج' },
    EGP: { name: 'Egyptian Pound', symbol: 'ج.م' },
    ERN: { name: 'Nakfa', symbol: 'Nfk' },
    ETB: { name: 'Ethiopian Birr', symbol: 'Br' },
    EUR: { name: 'Euro', symbol: '€' },
    USD: { name: 'US Dollar', symbol: '$' },
    UYU: { name: 'Peso Uruguayo', symbol: '$' },
    UZS: { name: 'Uzbekistan Sum', symbol: 'лв' },
    VEF: { name: 'Bolivar', symbol: 'Bs F' },
    VND: { name: 'Dong', symbol: '₫' },
    VUV: { name: 'Vatu', symbol: 'Vt' },
    WST: { name: 'Tala', symbol: 'T' },
    XAF: { name: 'CFA Franc BEAC', symbol: 'Fr' },
    XCD: { name: 'East Caribbean Dollar', symbol: '$' },
    XOF: { name: 'CFA Franc BCEAO', symbol: 'Fr' },
    XPF: { name: 'CFP Franc', symbol: 'Fr' },
    YER: { name: 'Yemeni Rial', symbol: '﷼' },
    ZAR: { name: 'Rand', symbol: 'R' },
    ZMW: { name: 'Zambian Kwacha', symbol: 'ZK' },
    ZWL: { name: 'Zimbabwe Dollar', symbol: '$' },
  };
  
  export default currencySymbols;